feat: add basic dark theme
Bashamega/ai-helper-tools pull request #4
Opened 2024-08-17 19:30 UTC by Rodney1988

added a few html element theme colors based on a toggle button, you can choose the exact changes. Let me know if all is good.

2024-08-18 02:51 UTC, Bashamega requested changes

2024-08-18 02:51 UTC, Bashamega commented on src/components/DarkModeToggle.jsx
> +    <button
In stead of a button, how about we add a dark mode toggle?

2024-08-18 16:17 UTC, Rodney1988 commented
hey @Bashamega, I changed it to a toggle button.

2024-08-19 02:16 UTC, Bashamega requested changes
Great work!

Please run `npm run prettier:write` to fix the failing checks

2024-08-19 09:10 UTC, Rodney1988 commented
there you go :)

2024-08-19 09:11 UTC, Bashamega approved these changes

2024-08-19 09:11 UTC, Bashamega commented
Great work:)

2024-08-19 09:11 UTC, merged