added contributing file
Bashamega/ai-helper-tools pull request #5
Opened 2024-08-17 22:16 UTC by Bridgetamana

2024-08-18 02:59 UTC, Bashamega requested changes

2024-08-18 02:59 UTC, Bashamega commented on contributing.md
> +Thank you for considering contributing to ai-helper-tools! We welcome contributions from everyone. Here’s a guide to help you get started.
```suggestion
Thank you for considering contributing to Gemini tools! We welcome contributions from everyone. Here’s a guide to help you get started.
```

2024-08-18 02:59 UTC, Bashamega commented on contributing.md
> +   ```
Add the step where the users setup the .env file

2024-08-19 23:10 UTC, Bridgetamana commented on contributing.md
> +   ```
How? please

2024-08-20 02:25 UTC, Bashamega commented on contributing.md
> +   ```
add the setups of copying the `.env.example` and with which key should they add and how to get it

2024-08-21 02:10 UTC, Bashamega approved these changes

2024-08-21 02:10 UTC, merged